version: '3.12'

services:
  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=weather_app_db
      - DB_USER=postgres
      - DB_PASSWORD=Akshay
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    ports:
      - "7000:9000"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    
    
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: weather_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akshay

volumes:
 postgres_data:
