version: '3.12'

services:
  web:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres_db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    ports:
      - "7000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres_db
    
    
  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
 postgres_data:
